### ISSUE TITLE
Don't prioritize "Liquidity required" in the default sorting.

### ISSUE THREAD

**Issue by Seer-Sir** [seer-pm/demo#206] opened 2024-12-17 05:15 UTC
![image](https://github.com/user-attachments/assets/5fa4506f-54f7-4630-bcf4-45b484fa990e)

**Comment by nvm1410** [comment] 2024-12-17 05:35
I think this is a duplicate of this issue: https://github.com/seer-pm/demo/issues/205

**Closed by nvm1410** 2024-12-17 05:35 UTC
Labels: enhancement
